# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  team_id = CredentialsManager::AppfileConfig.try_fetch_value(:team_id)
  app_identifier = CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)
  xcodeproj_name = 'BelAir_v2.xcodeproj'
  workspace_name = 'BelAir_v2.xcworkspace'
  project_name = 'BelAir_v2'
  output_name = 'BelAir_v2.ipa'
  profile_adhoc_name = 'BelAir Adhoc'
  profile_adhoc_uuid = 'ddee3d3d-408a-48bd-b42b-07d297e21901'
  apple_id = '1553254464'

  lane :install_profile do
    install_provisioning_profile(path: "../../BelAir_Adhoc.mobileprovision")
  end

  desc "Description of what the lane does"
  lane :adhoc do
    # install_profile

    Dir.chdir "../../../" do
      sh("ionic", "build")
    end

    update_project_provisioning(
      xcodeproj: xcodeproj_name,
      profile: "../../BelAir_Adhoc.mobileprovision",
      build_configuration: "Release",
      code_signing_identity: "iPhone Distribution"
    )

    update_project_team(
      path: xcodeproj_name,
      teamid: team_id
    )

    update_code_signing_settings(
      use_automatic_signing: false,
      path: xcodeproj_name,
      code_sign_identity: 'iPhone Distribution',
      profile_name: profile_adhoc_name,
      profile_uuid: profile_adhoc_uuid
    )

    build_app(
      scheme: project_name,
      workspace: workspace_name,
      include_bitcode: false,
      export_options: {
        method: "ad-hoc",
        provisioningProfiles: { 
          app_identifier => "BelAir Adhoc",
        }
      },
      output_name: output_name
    )

    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      apple_id: apple_id
    )
  end
end
