# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  team_id = CredentialsManager::AppfileConfig.try_fetch_value(:team_id)

  desc "Description of what the lane does"
  lane :adhoc do
    Dir.chdir "../../../" do
      sh("ionic", "build")
    end

    disable_automatic_code_signing

    update_project_provisioning(
      xcodeproj: "BelAir_v2.xcodeproj",
      profile: "../../BelAir_Adhoc.mobileprovision",
      build_configuration: "Release",
      code_signing_identity: "iPhone Distribution"
    )

    update_project_team(
      path: "BelAir_v2.xcodeproj",
      teamid: team_id
    )

    build_app(
      scheme: "BelAir_v2",
      workspace: "BelAir_v2.xcworkspace",
      include_bitcode: false,
      export_options: {
        method: "ad-hoc",
        provisioningProfiles: { 
          "be.irceline.aqmobile" => "BelAir Adhoc",
        }
      },
      output_name: "BelAir_v2.ipa"
    )
  end
end
