# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  lane :validate do
    validate_play_store_json_key(
      json_key: 'api-6392993945565658424-326639-91842bf073a9.json'
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do |options|
    # https://docs.fastlane.tools/actions/upload_to_play_store/
    if (options[:branch] == "master") then
      track = "alpha"
    else
      track = "internal"
    end


    upload_to_play_store(
      package_name: "com.gloow.ets",
      track: track,
      aab: 'app/build/outputs/bundle/release/app-release.aab',
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      skip_upload_apk: true,
      json_key: 'api-6392993945565658424-326639-91842bf073a9.json',
      release_status: 'completed'
    )
  end
end
